databases:
  - name: watchList
    plan: free
    databaseName: watchList
    user: watchList

services:
  - type: web
    name: watch-list
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: watch-list
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
